### ISSUE TITLE
Question on digital twin simulation

### ISSUE THREAD

**Issue by sebavarghese** [FrauThes/DigitalTwin-SIEM-integration#1]
Hi, 

I was trying out the digital twin simulation, and I am facing socket errors when I run plc1.py code. I have a few doubts for which I would like to get some help.

1) In README.md, the sequence of running .py code says, physical_process_bottle.py must be run before physical_process.py. But the code does just the opposite. However, I have tried both and it does not seem to work either way.
2) plc1.log always logs errors for both sensor outputs of plc2 and plc3. This is even before attack simulation.
3) I was wondering how the process simulation and sensor values get updated. I read the research doc and it says it is getting updated from the database. Are these hard coded? Or is this digital twin run along with its physical twin and the values are read from physical twin sensors?

Any help would be much appreciated.

**Comment by FrauThes** [comment]
Hi, 

if you receive socket errors the whole simulation cannot run appropriately and it is no wonder that you face these issues (1-3). 

Do you run the simulation stand-alone? Have you installed the correct Ubuntu version (18.04) on a VM (e.g. VirtualBox)? If you use another Ubuntu version it will not work properly. 
Have you executed the init.py?
**Have you uncommented the ".cmd" commands on the run.py and used the xterm alternative?** 

1. It should work either way.
2. If the plc1.log does get errors before the attack simulation, the communication between the PLCs might not run appropriately. If the physical processes are not running, the values will not be updated.
3. Yes, the sensor values get updated via the underlying database. The database is initiated with init.py. See the MiniCPS-documentation for further information (esp. get()- and set()-methods). There is currently no physical twin running along. The physical_process(_bottle).py determines the values when running. 

The soultion might be that you need the **older version of the cpppo-package as the newest version does not support ENIP-tags any more**. Try installing an older cpppo-version (4.1.x to 4.3.x should work).

**Comment by sebavarghese** [comment]
Hi, 

Thank you for your quick response.

I did try downgrading cpppo package from 4.4.2 to 4.1.0, and everything works perfectly fine :)

To answer your questions, I run only the standalone version of DT simulation and the ubuntu version is 18.04. Yes, I executed init.py and used xterm alternative upon commenting .cmd commands.

Thank you for your support.
