### ISSUE TITLE
Simulation showing static values 

### ISSUE THREAD

**Issue by sabahsuhail** [FrauThes/DigitalTwin-SIEM-integration#2]
Hi

I am trying to run (standalone) DigitalTwin-SIEM-integration simulation. I follow the following steps on VB Ubuntu 18.04
1. Install python2.7

`sudo apt install python2.7
alias python='/usr/bin/python2.7'
. ~/.bashrc`

2. Install mininet
`git clone git://github.com/mininet/mininet
cd mininet/util
./install.sh -a`

3. Install MiniCPS:
`sudo pip install minicps`

4.
`git clone https://github.com/FrauThes/DigitalTwin-SIEM-integration.git
cd DigitalTwin-SIEM-integration/src
sudo python2 init.py
sudo python2 run.py `

I also tried `openvswitch service (service openvswitch-switch start) ` as suggested by you earlier. 

I mentioned all steps here just to recheck the wrong settings because every time I run this simulation  I am getting **static values** as shown in the **image**. 
Kindly please help me to sort out this issue. thank  you 

![static_op](https://user-images.githubusercontent.com/14018340/127620398-6eba8871-40ba-4e75-9e63-ef1f0a988b63.png)

**Comment by FrauThes** [comment]
Hi, 

have you downgraded the cpppo-package? (4.1.x to 4.3.x should work)
Again, the newest version does not support ENIP-tags any more. 

Looks like communication between the PLCs does not work, and thus, the values remain the same...

**Comment by sabahsuhail** [comment]
Hi 
I just realize downgrading it after you mentioned it for the other simulation too. It's working now. Many thanks

**Comment by FrauThes** [comment]
Issue closed
