### ISSUE TITLE
CAR

### ISSUE THREAD

**Issue by cailv** [FrauThes/DigitalTwin-SIEM-integration#3]
Can this system be deployed in a car? I plan to expand an IDS that detects abnormal information of cars

**Comment by FrauThes** [comment]
You could implement the SIEM-part in a car, I suppose. 
The digital twin part, however, is mapped for an industrial filling plant. This part would not make sense for implementation.

**Comment by cailv** [comment]
Hello, senior. Can you give me a complete running screenshot of this project when it is fully started? I could start it the first time, but it failed the second time. Can you send me a clear screenshot of the virtual machine with those windows? My Google email: ssxzwwsjz@gmail.com. I will cite your paper if I can!
