### ISSUE TITLE
ERROR enip _receive: argument should be integer or bytes-like object, not 'str'

### ISSUE THREAD

**Issue by casasso83** [FrauThes/DigitalTwin-SIEM-integration#4]
After successfully installing all dependencies and degrading cpppo-package to be between versions 4.1.x to 4.3.x, I receive issues like the following screenshot:

![Screenshot from 2022-09-27 13-35-20](https://user-images.githubusercontent.com/54518656/192630113-05c8c311-2577-4ac9-8ab0-125ecba9e970.png)

Where would I need to make changes to the python files to resolve these issues?

**Comment by FrauThes** [comment]
Seems like an conversion-error. Without more infos, I would recommend to check the values of the tags. 
Also, I would encourage you to try different  (earlier) versions of the cpppo-package (4.1.x).

**Comment by FrauThes** [comment]
![Clipboard - 25  Mai 2020 17_15](https://user-images.githubusercontent.com/51534817/194010915-7c6ef6d5-3da9-4348-b7cb-0e53b1aee204.png)

You should also check the ### data part in ### utils.py 
The naming of the tags have to be the same in ### utils.py and ### plc1.py and so on (see interlock comments). Also the values have to be **REAL** or **INT** depending on the tag in question...

**Comment by casasso83** [comment]
After changing OS versions of Ubuntu to 18.04, using only Python 2.7, and downgrading cpppo to version 4.1.0, the errors I received were resolved.
